#!/usr/bin/env bash

set -e

PYTHON=python


PYTHONPATH=src $PYTHON \
    src/facto/algorithm/sim/main1_sample_masked_success_rates.py \
    --mask_proportions 0 0.01 0.1 0.5 0.9 \
    --max_shots 200_000 \
    --max_semiprime 10000 \
    --save_resume_path assets/masked_success_stats.csv


# Single run.
PYTHONPATH=src $PYTHON \
    src/facto/algorithm/estimates/main1_generate_cost_table_data.py \
    --params_csv_path parameterizations/rsa-single-run-params.csv \
    --out_csv_path out/rsa-single-run-cost-variations.csv

PYTHONPATH=src $PYTHON \
    src/facto/algorithm/estimates/main1_generate_cost_table_data.py \
    --params_csv_path parameterizations/ff-dh-short-single-run-params.csv \
    --out_csv_path out/ff-dh-short-single-run-cost-variations.csv

PYTHONPATH=src $PYTHON \
    src/facto/algorithm/estimates/main1_generate_cost_table_data.py \
    --params_csv_path parameterizations/ff-dh-schnorr-single-run-params.csv \
    --out_csv_path out/ff-dh-schnorr-single-run-cost-variations.csv


# Large tradeoff factor s.
PYTHONPATH=src $PYTHON \
    src/facto/algorithm/estimates/main1_generate_cost_table_data.py \
    --params_csv_path parameterizations/rsa-large-s-params.csv \
    --out_csv_path out/rsa-large-s-cost-variations.csv

PYTHONPATH=src $PYTHON \
    src/facto/algorithm/estimates/main1_generate_cost_table_data.py \
    --params_csv_path parameterizations/ff-dh-short-large-s-params.csv \
    --out_csv_path out/ff-dh-short-large-s-cost-variations.csv

PYTHONPATH=src $PYTHON \
    src/facto/algorithm/estimates/main1_generate_cost_table_data.py \
    --params_csv_path parameterizations/ff-dh-schnorr-large-s-params.csv \
    --out_csv_path out/ff-dh-schnorr-large-s-cost-variations.csv


# All combinations.
PYTHONPATH=src $PYTHON \
    src/facto/algorithm/estimates/main1_generate_cost_table_data.py \
    --params_csv_path parameterizations/rsa-params.csv \
    --out_csv_path out/rsa-cost-variations.csv

PYTHONPATH=src $PYTHON \
    src/facto/algorithm/estimates/main1_generate_cost_table_data.py \
    --params_csv_path parameterizations/ff-dh-short-params.csv \
    --out_csv_path out/ff-dh-short-cost-variations.csv

PYTHONPATH=src $PYTHON \
    src/facto/algorithm/estimates/main1_generate_cost_table_data.py \
    --params_csv_path parameterizations/ff-dh-schnorr-params.csv \
    --out_csv_path out/ff-dh-schnorr-cost-variations.csv
